---

# TODO: add retries, occasionally get failures in packet
- name: "{{ packet_node_state }}" physical servers in packet cloud
  packet_node:
    project_id: "{{ lookup('env','PACKET_PROJECT_ID') }}"
    hostnames: "stx-workshop-%d"
    count: "{{ num_students }}"
    operating_system: "{{ packet_os }}"
    plan: "{{ packet_plan }}"
    facility: "{{ packet_facility }}"
    state: "{{ packet_node_state }}"
    tags: 
      - "{{ workshop_tag }}"
  register: packet_nodes

- debug:
    msg: "{{ packet_nodes }}"
    verbosity: 2