---

- name: ensure required packages are present
  apt:
    name: "{{ hypervisor_packages }}"
    update_cache: True 
    cache_valid_time: 600

- name: ensure libvirt-python is installed (for virt module)
  apt:
    name: "python-libvirt"

# For docker
- name: ensure requirements for pip are installed
  apt:
    name: "python-pip"
    state: latest
    update_cache: true

- name: install ansible docker modules pip requirements 
  pip:
    name: docker-py
