---

hypervisor_use_apt_mirrors: True

iso_image: ""
iso_image_install_dir: "/var/lib/libvirt/images"

controller_name: "simplex-controller-0"

# FIXME: can get index another way without specifiying here?
controller_disks:
  - name: "disk0"
    index: 0
    size: 600
  - name: "disk1"
    index: 1
    size: 200
  - name: "disk2"
    index: 2
    size: 200

bridge_basename: "stxbr"
# FIXME: this will fall within 10/8 from packet
external_netmask_cidr: 24
external_ip: "10.10.10.1/{{ external_netmask_cidr }}"
external_network: "10.10.10.0/{{ external_netmask_cidr }}"

lvm_services:
  - lvm2-lvmetad.service
  - lvm2-lvmetad.socket