---

- name: setup message of the day
  copy:
    dest: "/etc/motd"
    content: |
      **************************************************************************
      #                                                                        #
      #      This system is only for use during a StarlingX workshop.          #
      #                                                                        #
      **************************************************************************

- name: disable metadata warnings 
  copy:
    dest: "/var/lib/cloud/instance/warnings/.skip"
    content: |
      empty

- name: allow password ssh logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication yes'
    backrefs: yes
  notify: restart ssh

- name: ensure sudo group users can sudo without a password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: ensure a student users exists
  user:
    name: "{{ student_name }}"
    password: "{{ student_password  | password_hash('sha512', 'insecuresalt') }}"
    groups: 
     - sudo
    shell: "/bin/bash"
    state: present

- name: create a file that contains all access information
  template:
    src: "access.txt"
    dest: "/tmp/access.txt"

- name: fetch /tmp/access.txt
  fetch:
    src: "/tmp/access.txt"
    dest: "./access.txt"
    flat: True
  run_once: True

